### ISSUE TITLE
RemoteUpdateManager recipes

### ISSUE THREAD

**Issue by opus-nbonenberger** [autopkg/precursorca-recipes#12]
@precursorca Thanks for these recipes. Problem is, I need both. When running them on one Munki repo, I can't tell which is which as both are imported with identical names. Can you adjust that?  Thanks!

**Comment by precursorca** [comment]
I haven’t had any success in my testing yet but I will keep trying and let you know if I ever fix it.


---
Alex Narvey
***@***.***

**Comment by precursorca** [comment]
I don't know why I never noticed before but the M1 pkg was pointing to the Intel download.
I have corrected that. It is possible to download both recipes with overrides and they get deployed according to the Supported Architecture: Arm64 or x86_64.
