### ISSUE TITLE
Webex using old download links

### ISSUE THREAD

**Issue by joshnovotny** [autopkg/precursorca-recipes#18]
Hello,

Webex has been stuck on 44.8.0.30404 for two versions now. Looking at their site, they offer admin downloads here:

https://help.webex.com/en-us/article/nw5p67g/Webex-App-%7C-Installation-and-automatic-upgrade#Cisco_Reference.dita_1b73bf74-1da0-4e2f-8e3b-e13bfbd89e49

And the two relevant links being:

Intel:
https://binaries.webex.com/webex-macos-intel/Webex.dmg

Apple Silicon:
https://binaries.webex.com/webex-macos-apple-silicon/Webex.dmg

Which download the latest 44.10.1.31028 DMG.

**Comment by precursorca** [comment]
Thank you.

I updated the webex.download.recipe to the newer intel URL and provided both the ARM and Intel URL schemes in the description.

---
Alex Narvey
***@***.***

**Comment by joshnovotny** [comment]
Works great, thanks for the fast response!
